
/*

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
From leetcode : https://leetcode.com/problems/find-the-difference/

*/


char findTheDifference(char * s, char * t){
    int i,a[26]={0}; //array to store frequence of each letter
    for(i=0;i<strlen(s);i++) //for loop to see which letter is used
    {
        a[s[i]-'a']++; 
        a[t[i]-'a']--;
    }
        
    a[t[i]-'a']--; //with this for loop we didn't check the last letter of t (t has one more letter)
    for(i=0;i<26;i++) {
        if(a[i]==-1) {
            return i + 'a';
        }
                          
    }
                
    return 0;
}
